plugins {
    id 'com.android.application'
}

android {
    namespace 'cloud.kasmui.hadits'
    compileSdk 35

    defaultConfig {
        applicationId 'cloud.kasmui.hadits'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '2.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
